title: Learning about GP with Jekyll
author: Lucas Magalhães
email: lucasdarosa.ti@gmail.com
description: Learning about GP with Jekyll

# social links
twitter_lucaormagalhaes: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_lucasrmagalhaes: your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
