title: GitHub Pages with Jekyll.
author: Lucas Magalhães
email: lucasdarosa.ti@gmail.com
description: GitHub Pages with Jekyll by Lucas Magalhães.
theme: minima

# Social Links
twitter_lucaormagalhaes: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_lucasrmagalhaes:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
